/*------------------------------------------------------------------------
 *  RAJZEL: 2D First-Arrival Traveltime Modelling and Tomography Code 
 *  using an Eikonal Solver and adjoint-state method without ray-tracing
 *
 *  Authors:
 *  -----------  
 * 
 *  D. Koehn    (FATT code + updates)
 *  D. De Nil   (FATT code + updates)
 *  
 *  In case of questions contact the author:
 *	Dr. Daniel Koehn, Kiel University, Institute of Geoscience,
 *	Otto-Hahn-Platz 1, D-24098 Kiel, Germany, ph: +49 431 880 3878,
 *	mailto:dkoehn@geophysik.uni-kiel.de,
 *	Homepage: http://www.geophysik.uni-kiel.de/~dkoehn
 *
 *  RAJZEL is free software: you can redistribute it and/or modify 
 *  it under the terms of the GNU General Public License as published by 
 *  the Free Software Foundation, version 2.0 of the License only. 
 *  
 *  RAJZEL is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU General Public License for more details. 
 *  
 *  You should have received a copy of the GNU General Public License 
 *  along with RAJZEL (see file LICENSE.md) 
 *
 *  If you show modelling/inversion results in a paper or presentation please 
 *  give a reference to the following papers: 
 *  
 *  Thank you for your co-operation, 
 *  Daniel Koehn
 * 
 *  ---------------------------------------------------------------------------------------*/

#include "fd.h"           /* general include file */
#include "globvar.h"      /* definition of global variables  */

int main(int argc, char **argv){

/* variables in main */
int j, i, ntr=0, nshots=0, ** recpos=NULL;
float ** srcpos=NULL;
float  **S, ** TT, ** Vp;
double time1, time8;
char ext[10], *fileinp, *fileinp1;	

/* FA traveltime data*/
float * Tmod, * Tobs, * Tres;

/* Initialize MPI environment */
MPI_Init(&argc,&argv);
MPI_Comm_size(MPI_COMM_WORLD,&NP);
MPI_Comm_rank(MPI_COMM_WORLD,&MYID);

setvbuf(stdout, NULL, _IONBF, 0);

if (MYID == 0){
   time1=MPI_Wtime(); 
   clock();
}
		
/* print program name, version etc to stdout*/
if (MYID == 0) info(stdout);

/* read parameters from parameter-file (stdin) */
fileinp=argv[1];
fileinp1=argv[2];
FP=fopen(fileinp,"r");
if(FP==NULL) {
	if (MYID == 0){
		printf("\n==================================================================\n");
		printf(" Cannot open Rajzel input file %s \n",fileinp);
		printf("\n==================================================================\n\n");
		err(" --- ");
	}
}


/* read input file *.inp */
read_par(FP);

if (MYID == 0) note(stdout);

/* open log-file (each PE is using different file) */
/*	fp=stdout; */
sprintf(ext,".%i",MYID);  
strcat(LOG_FILE,ext);

if ((MYID==0) && (LOG==1)) FP=stdout;
else FP=fopen(LOG_FILE,"w");
fprintf(FP," This is the log-file generated by PE %d \n\n",MYID);

/* output of parameters to log-file or stdout */
if (MYID==0) write_par(FP);
	
/* NXG, NYG denote size of the entire (global) grid */
NXG=NX;
NYG=NY;

recpos=receiver(FP, &ntr, 1);

if(N_STREAMER>0){
  free_imatrix(recpos,1,3,1,ntr);
}

/* FA travetime data at receiver positions */
Tmod = vector(1,ntr);

if(INVMAT){
   Tobs = vector(1,ntr);
   Tres = vector(1,ntr);
}	

/* memory allocation for travetimes */
TT =  matrix(1,NY,1,NX);
Vp =  matrix(1,NY,1,NX);
S = matrix(1,NY,1,NX);

/* If INVMAT!=0 deactivate unnecessary output */
INFO=0;

/* If INVMAT==0 allow unnecessary output */
if(INVMAT==0){
   INFO=1;
}

/*if (MYID == 0) info_mem(stdout,NLBFGS_vec,ntr);*/

/* Reading source positions from SOURCE_FILE */ 	
srcpos=sources(&nshots);

/* Initiate MPI shot parallelization */
init_MPIshot(nshots);

/* read/create P-wave velocity */
if (READMOD){
    readmod(Vp); 
}else{
    model(Vp);
}

/* calculate slowness S from Vp model*/
calc_S(Vp,S); 

/* solve Eikonal forward problem only */
/* ---------------------------------- */
if(INVMAT==0){
   forward(S,TT,Tmod,srcpos,nshots,recpos,ntr);
}

/* First-Arrival Traveltime tomography based on the adjoint method */
/* --------------------------------------------------------------- */
if(INVMAT==1){
   fatt(Vp,S,TT,Tmod,Tobs,Tres,srcpos,nshots,recpos,ntr,fileinp1);
}
          
/* 1D linear gradient model estimation by grid search */
/* -------------------------------------------------- */
if(INVMAT==2){
   grid_search(Vp,S,TT,Tmod,Tobs,Tres,srcpos,nshots,recpos,ntr);
}

/* deallocation of memory */
free_matrix(Vp,1,NY,1,NX);
free_matrix(TT,1,NY,1,NX);
free_vector(Tmod,1,ntr);
free_matrix(S,1,NY,1,NX);

if(INVMAT){

   free_vector(Tobs,1,ntr);
   free_vector(Tres,1,ntr);

}

/* free memory for global source positions */
free_matrix(srcpos,1,8,1,nshots);
 
MPI_Barrier(MPI_COMM_WORLD);

if (MYID==0){
	fprintf(FP,"\n **Info from main (written by PE %d): \n",MYID);
	fprintf(FP," CPU time of program per PE: %li seconds.\n",clock()/CLOCKS_PER_SEC);
	time8=MPI_Wtime();
	fprintf(FP," Total real time of program: %4.2f seconds.\n",time8-time1);		
}

fclose(FP);

MPI_Finalize();
return 0;	

}/*main*/
